#!/bin/bash
echo '---[ Deleting the Backend samples folder and Analyzer analysis Folder ]---'
rm -rf Backend/analyzer/samples/ StaticAnalysis/analysis/ DynamicAnalysis/analysis/
mkdir StaticAnalysis/analysis/ Backend/analyzer/samples/
echo '---[ Cleaning the Neo4J Database ]---'
(
	# TODO Stop neo4j Server, delete data/graph.db/* to remove old property nodes
	cd Neo4J
	python -c 'from msneo import clean_all; clean_all()'
)
echo '---[ Cleaning the Postgesql Database ]---'
(
	cd Backend
	./cleandb
)
echo '---[ Done ]---'
