from py2neo import Graph, Node
import re

pw = 'msneo' # After changing password from default password neo4j to msneo

def add_attribute(node, datadict, attribute, regex=None, upper=False):
    if attribute not in datadict: return
    if regex and not regex.match(datadict[attribute]): return

    if datadict[attribute] != '':
        node[attribute] = datadict[attribute]
        if upper: node[attribute] = node[attribute].upper()
    return node


# Transfer an Android Application node with feature vectors / attributes generated by the static or dynamic analyzer
def create_node(datadict): # TODO Rename to create node
    print 'Transferring data to Neo4J database'
    graph = Graph(password=pw)
    tx = graph.begin()

    n = Node('Android')

    # TODO: Move compiled regex to somewhere only executed once
    r_md5    = re.compile(r'[a-fA-F\d]{32}')
    r_sha1   = re.compile(r'[a-fA-F\d]{40}')
    r_sha256 = re.compile(r'[a-fA-F\d]{64}')

    add_attribute(n, datadict, 'md5', regex=r_md5, upper=True)
    add_attribute(n, datadict, 'sha1', regex=r_sha1, upper=True)
    add_attribute(n, datadict, 'sha256', regex=r_sha256, upper=True)
    add_attribute(n, datadict, 'activities')
    add_attribute(n, datadict, 'package_name')
    add_attribute(n, datadict, 'apk_name')
    add_attribute(n, datadict, 'sdk_version')
    add_attribute(n, datadict, 'app_permissions')
    add_attribute(n, datadict, 'api_permissions')
    #add_attribute(n, datadict, 'api_calls') # TODO List of lists don't work yet
    add_attribute(n, datadict, 'features')
    add_attribute(n, datadict, 'intents')
    add_attribute(n, datadict, 's_and_r')
    add_attribute(n, datadict, 'interesting_calls')
    add_attribute(n, datadict, 'urls')
    add_attribute(n, datadict, 'networks')
    add_attribute(n, datadict, 'providers')
    add_attribute(n, datadict, 'included_files')
    add_attribute(n, datadict, 'detected_ad_networks')
    tx.create(n)
    tx.commit()

def clean_all():
    graph = Graph(password=pw)
    tx = graph.begin()
    tx.run('MATCH (n:Android) DELETE n')
    tx.commit()

def show_graph():
    graph = Graph(password=pw)
    graph.run('MATCH (n:Android) return n')
    graph.open_browser()
