#!/bin/bash
[[ $# -ne 3 ]] && echo "Usage: $0 <Source Directory> <Target Directory> <Number of Samples>" && exit 1
DIR_ALL_SAMPLES="$1"
DIR_TRAINING_SAMPLES="$2"
mkdir "$DIR_TRAINING_SAMPLES"
ls "$DIR_ALL_SAMPLES" | shuf -n"$3" | while read f; do cp "${DIR_ALL_SAMPLES}/${f}" "${DIR_TRAINING_SAMPLES}"; done
