#!/bin/bash
[[ $# -ne 1 ]] && echo "Usage: $0 <analysis-logfile>" && exit 1
[[ ! -f "$1" ]] && echo 'Need a non-empty analysis logfile' && exit 2
ORANGE="\e[01;32m"
OFF="\e[m"
SAMPLES=$(wc "$1" | awk '{print $1}' | tr -d '\n')
TOTAL_TIME=$(cat "$1" | awk '{print $7}' | paste -sd+ | bc)
echo -e "Seconds taken for ${ORANGE}$SAMPLES${OFF} samples: $TOTAL_TIME"
AVG=$(echo "scale=5; $TOTAL_TIME/$SAMPLES" | bc)
echo "Average per sample is (in seconds): $AVG"
SORTED=$(LC_ALL=C sort -gk7 "$1" | column -t)
echo "$SORTED" | head -n1
echo "$SORTED" | tail -n1
